import { useRef, useState, useCallback } from 'react'
import { NavLink, Outlet, Navigate } from 'react-router-dom'
import { Button, SearchField } from '../components/ui.jsx'
import { useAuth } from '../hooks/useAuth.jsx'
const nav = ['Dashboard', 'My Profile', 'Resume & ATS', 'Jobs', 'Applications', 'Interviews', 'AI Mock Interview', 'Offers']
export function DashboardLayout() {
  // useState: controls the responsive sidebar.
  const [open, setOpen] = useState(false); const searchRef = useRef(null); const { user, logout } = useAuth()
  const [search, setSearch] = useState('')
  const handleSearchChange = useCallback((event) => setSearch(event.target.value), [])
  if (!user) return <Navigate to="/login" replace />
  return <div className="min-h-screen bg-slate-50"><aside className={`fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-slate-200 bg-slate-950 px-4 py-5 text-slate-300 transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><NavLink to="/student" className="mb-9 flex items-center gap-3 px-2 text-xl font-bold text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-500">N</span>NexHire</NavLink><nav className="space-y-1">{nav.map((item, i) => <button key={item} onClick={() => { setOpen(false); if (!i) window.scrollTo({ top: 0, behavior: 'smooth' }) }} className={`focus-ring flex w-full rounded-xl px-3 py-3 text-left text-sm font-medium transition ${i === 0 ? 'bg-indigo-500/20 text-white' : 'hover:bg-white/5 hover:text-white'}`}>{item}</button>)}</nav><p className="mt-auto rounded-xl bg-white/5 p-3 text-xs leading-5 text-indigo-200">Phase 0 demo workspace<br />Experiment 3.2 · React Hooks</p></aside>{open && <button aria-label="Close navigation" className="fixed inset-0 z-20 bg-slate-950/40 lg:hidden" onClick={() => setOpen(false)} />}<div className="lg:pl-72"><header className="sticky top-0 z-10 flex min-h-20 items-center gap-3 border-b border-slate-200 bg-slate-50/95 px-4 backdrop-blur sm:px-7"><Button variant="secondary" className="px-3 lg:hidden" onClick={() => setOpen(true)}>☰</Button>{/* useRef: focuses this top search input. */}<SearchField inputRef={searchRef} value={search} onChange={handleSearchChange} /><Button variant="ghost" className="hidden px-3 sm:inline-flex" onClick={() => searchRef.current?.focus()}>⌕</Button><button className="focus-ring ml-auto grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white" aria-label="Notifications">♧</button><div className="hidden items-center gap-3 border-l border-slate-200 pl-4 sm:flex"><span className="grid h-9 w-9 place-items-center rounded-full bg-indigo-100 text-sm font-bold text-indigo-700">{user?.initials ?? 'NH'}</span><div><p className="text-sm font-semibold">{user?.name ?? 'Guest user'}</p><button className="text-xs text-slate-500 hover:text-indigo-600" onClick={logout}>Demo sign out</button></div></div></header><main className="mx-auto max-w-7xl p-4 sm:p-7"><Outlet context={{ globalSearch: search }} /></main></div></div>
}
